/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuienesSomosRouteImport } from './routes/quienes-somos'
import { Route as PoliticasPublicasRouteImport } from './routes/politicas-publicas'
import { Route as InvestigacionRouteImport } from './routes/investigacion'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'

const QuienesSomosRoute = QuienesSomosRouteImport.update({
  id: '/quienes-somos',
  path: '/quienes-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticasPublicasRoute = PoliticasPublicasRouteImport.update({
  id: '/politicas-publicas',
  path: '/politicas-publicas',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigacionRoute = InvestigacionRouteImport.update({
  id: '/investigacion',
  path: '/investigacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/investigacion': typeof InvestigacionRoute
  '/politicas-publicas': typeof PoliticasPublicasRoute
  '/quienes-somos': typeof QuienesSomosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/investigacion': typeof InvestigacionRoute
  '/politicas-publicas': typeof PoliticasPublicasRoute
  '/quienes-somos': typeof QuienesSomosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/investigacion': typeof InvestigacionRoute
  '/politicas-publicas': typeof PoliticasPublicasRoute
  '/quienes-somos': typeof QuienesSomosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/investigacion'
    | '/politicas-publicas'
    | '/quienes-somos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/investigacion'
    | '/politicas-publicas'
    | '/quienes-somos'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/investigacion'
    | '/politicas-publicas'
    | '/quienes-somos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  InvestigacionRoute: typeof InvestigacionRoute
  PoliticasPublicasRoute: typeof PoliticasPublicasRoute
  QuienesSomosRoute: typeof QuienesSomosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quienes-somos': {
      id: '/quienes-somos'
      path: '/quienes-somos'
      fullPath: '/quienes-somos'
      preLoaderRoute: typeof QuienesSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politicas-publicas': {
      id: '/politicas-publicas'
      path: '/politicas-publicas'
      fullPath: '/politicas-publicas'
      preLoaderRoute: typeof PoliticasPublicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigacion': {
      id: '/investigacion'
      path: '/investigacion'
      fullPath: '/investigacion'
      preLoaderRoute: typeof InvestigacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  InvestigacionRoute: InvestigacionRoute,
  PoliticasPublicasRoute: PoliticasPublicasRoute,
  QuienesSomosRoute: QuienesSomosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
